### ISSUE TITLE
Employee view details

### ISSUE THREAD

**Issue by R3DniC** [Team-GAKN/pms_employee_management_frontend#7]
## Description
Upon selecting an employee in the employee view, the employee details should be displayed as per the wireframe "Mitarbeiterdetails."

## Todo
- Display the first and last name, phone number, postal code (PLZ), town, street, and qualifications of the employee.
- Place a green edit button at the top left corner of the employee details window.

## For Developer
-

## For Reviewer
-

**Comment by topgggggg** [comment]
Falsely opened. Has been done in another issue.
